### ISSUE TITLE
Command::Wait not working, gives 'No command specified'

### ISSUE THREAD

**Issue by harleypig** [yanick/Taskwarrior-Kusarigama#22]
System: Linux Mint 18.3 Sylvia
    Kernel: Linux 4.13.0-16-generic
    Task: 2.6.0 (20a2bbd) (compiled yesterday--03/03/18)
    perl: 5.022001
    perlbrew: 0.82 (installed via package manager)
    Taskwarrior::Kusarigama: 0.8.0 (per pmver, updated via cpanm today--03/04/18)

`cpan-outdated -p` shows only `DB_File` and `mod_perl`, which don't have anything to do with your package as far as I can tell.

I have some custom setup in the way I run task, but the specific point is [here](https://github.com/harleypig/dotfiles/blob/master/.bash_sources.d/taskwarrior#L12).  All of my aliases and functions use that function to call task.  However, I get the same problem if I call task directly.

I added your example `PrintStage` module and added `kusarigama.plugins=PrintStage` to my `.taskrc`, and I get the following output:

    [task list]
    
    5 tasks
    launch stage: Taskwarrior::Kusarigama::Plugin::PrintStage
    exit stage: Taskwarrior::Kusarigama::Plugin::PrintStage

So I know things are installed properly.  I set the uda key to `kusarigama.plugins=PrintStage,Command::Wait` and `t 22 wait` gave me

    t 21 wait
    No command specified - assuming 'information'.
    launch stage: Taskwarrior::Kusarigama::Plugin::PrintStage
    No matches.
    exit stage: Taskwarrior::Kusarigama::Plugin::PrintStage

I have never used Moose, or Moo. I don't know how to debug this. I did copy the Command::Wait module to my task lib dir and added two print statements, one outside functions and one inside the `do_command` function. The print outside the function is seen, but the one inside the function is not seen when `t 21 wait` is called. I also tried `t wait 21` but got the same results.

**Comment by yanick** [comment]
I think I know: you need to do `task-kusarigama add Command::Wait` so that  in addition of the command being added to kusarigama.plugins, a fake/dummy report `wait` will be created (which will allow `task wait` to run and let kusarigama takes care of the details).

**Comment by harleypig** [comment]
You are partially correct. I went back and re-read the README and realized I had not run the `task-kusarigama add` command, but when I did that the only thing it did was re-order the `kusarigama.plugins` uda.

The steps following that included the `task-kusarigama install` command, but I had already run that initially. I took a chance and ran that again, and it added the `report.wait.*` config lines. At that point the `t 21 wait` command worked.

So, every time you add a plugin you need to run the install command. It looks like you will have to manually uninstall plugins though. Not a big deal. Thanks for the kick in the right direction.
