### ISSUE TITLE
@projname leaves leading space in description

### ISSUE THREAD

**Issue by harleypig** [yanick/Taskwarrior-Kusarigama#23]
https://github.com/yanick/Taskwarrior-Kusarigama/blob/eb3ed7813e510bdda82203b477826f58fb37fe7a/lib/Taskwarrior/Kusarigama/Plugin/ProjectAlias.pm#L21

If `task add @test do this` is called, then run `task` you'll see the following:

    ID Project Description
    87 test     do this
    
    1 task

That extra space annoys me and tweaks my ocp (obsessive-compulsive personality).

At first I tried changing the regex to `s/(?:^|\s)\@(\w+)\s*//` but that compresses arguments poorly.

Then I just decided to get rid of leading spaces, on the next line adding this: `$desc =~ s/^\s+//;`

It seems to work well, but it's got some obvious possible drawbacks. Cheif among them, if I do 'task add @test ' task I want to begin with a space'` that will not work.

I wouldn't ever do that, but I don't know how likely or common that would be.

Do you have another way to do this?

Edit: Added my changes to regex so the sentence makes sense.

**Comment by yanick** [comment]
I think that would work. We could also do `s/(^|\s)\@(\w+)\s+/$1/` or something of the type.
