### ISSUE TITLE
GitCommit produces a Path::Tiny error

### ISSUE THREAD

**Issue by pjf** [yanick/Taskwarrior-Kusarigama#9]
I did a `task-kusarigama add GitCommit`, and now whenever I run `task` I get (in addition to the regular report of what I should be working on):

> Path::Tiny paths require defined, positive-length parts at /home/pjf/perl5/lib/perl5/Taskwarrior/Kusarigama/Core.pm line 65.

Line 65 in that file is:

```
has data_dir => sub {
    path( $_[0]->data );   # <--- THIS ONE HERE
};
```

I'm not sure what `data_dir` is supposed to return, but I'm guessing it's `task`'s data dir, which on my system is the default of `~/.task` (and not defined in my config, because I'm using the defaults).

I would totally debug this more but it's 3:20am in Australia and thus a silly time for me to be awake. :)

Much love,

~ pjf

**Comment by yanick** [comment]
First, don't answer that if you are still awake. Go to bed.

When you wake up, let me know what `task version` gives you. I suspect you are running a version of taskwarrior that still implement version 1 of its hooks (https://taskwarrior.org/docs/hooks.html). v2 (https://taskwarrior.org/docs/hooks2.html) provides a few additional goodies to the plugins, including `data`, which points to the task data dir. 

And while you check that, I'll beef up the code and set a reasonable default for the data dir. New version will appear soon. :-)

**Comment by pjf** [comment]
Going to bed!

Also, info:

> `$ task version`
> 
> task 2.5.1 built for linux
> Copyright (C) 2006 - 2016 P. Beckingham, F. Hernandez.
> 
> Taskwarrior may be copied only under the terms of the MIT license, which may be found in the Taskwarrior source kit.
> 
> Documentation for Taskwarrior can be found using 'man task', 'man taskrc', 'man task-color', 'man task-sync' or at
> http://taskwarrior.org
> 
> Path::Tiny paths require defined, positive-length parts at /home/pjf/perl5/lib/perl5/Taskwarrior/Kusarigama/Core.pm line 65.

**Comment by yanick** [comment]
You /do/ have the latest version.

Oh. Look into `~/.task/hooks/*-kusarigama.pl`, do the script looks like

```
#!/usr/bin/env perl

use Taskwarrior::Kusarigama::Hook;

Taskwarrior::Kusarigama::Hook->new( raw_args => \@ARGV )->run_event( 'add' );
```

I just saw that while `task-kusarigama install` would do the right thing, I was missing the 
backslash in the POD... <.<

**Comment by pjf** [comment]
I used `task-kusarigama install`, and my hooks look exactly like yours.

I'm awake and finding coffee now, then I think it's time for me to do some debugging. :)

**Comment by pjf** [comment]
It looks like we're not getting any `raw_args` at all. That's very odd!

```
$VAR1 = bless( {
                 'raw_args' => [],
                 'exit_on_failure' => '1'
               }, 'Taskwarrior::Kusarigama::Plugin::GitCommit' );
```

Still investigating.

**Comment by pjf** [comment]
`Kusarigama::Hook` is getting the raw args properly, and is extracting the `data` dir from that.

It doesn't seem to be passing it on to the `GitCommit` plugin.

I'm still not sure why.

**Comment by pjf** [comment]
And bug found! See PR #12 for a fix. :)

This was a very clever way to get me familiar with the internals of TW::K. :)

**Comment by yanick** [comment]
Oh yes, absolutely. Clever ploy. Not a leftover after a name change. Absolutely. ;-)
